"use client";
import Sidebar from '@/components/Sidebar';
import Header from '@/components/Header';
import styles from '../static.module.css';

export default function PrivacyPolicy() {
    return (
        <div className={styles.container}>
            <Sidebar />
            <main className={styles.mainContent}>
                <Header title="Privacy Policy" />
                <div className={styles.content}>
                    <div className={styles.card}>
                        <h1 className={styles.title}>Privacy Policy</h1>
                        <p className={styles.text}>
                            At TrendFinder, we value user privacy.
                            <br /><br />
                            When you visit our website, cookies may be used to improve site performance and user experience.
                            <br /><br />
                            Third-party advertising providers, such as Google Adsense, may use cookies to show ads based on a user's interests.
                            <br /><br />
                            Analyses and suggestions provided on our website are generated by AI-supported systems and are for informational purposes only. TrendFinder does not guarantee the accuracy or results of the information provided.
                            <br /><br />
                            Users can disable cookies through their browser settings.
                        </p>
                    </div>
                </div>
            </main>
        </div>
    );
}

